name: Update interactions
on: [workflow_dispatch]

jobs:
  update-interactions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.1.0
      - run: pnpm i
      - name: Update interactions
        env:
          DEV_CLIENT_ID: ${{ secrets.DISCORD_DEV_CLIENT_ID }}
          DEV_BOT_TOKEN: ${{ secrets.DISCORD_DEV_BOT_TOKEN }}
          DEV_CLIENT_PUBLIC_KEY: ${{ secrets.DISCORD_DEV_PUBLIC_KEY }}
        run: | 
          mkdir build/build-dev/data
          npm run build:dev