name: Update interactions
on: [workflow_dispatch]

jobs:
  update-interactions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.1.0
      - run: pnpm i
      - name: Update interactions
        env:
          CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          CLIENT_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          MONGO_AUTH: ${{ secrets.MONGO_AUTH }}
        run: | 
          mkdir build/build/data
          npm run build